"""Two-stage filter from the TZ (section 4):

Stage 1 — free, no LLM: quick keyword/contact regex pre-filter to drop
obvious junk (discussions, questions, reposts) before spending tokens.

Stage 2 — one Claude Haiku call that both classifies (is this a real
service ad?) and extracts the structured fields for the CRM card.
The original post text itself is NEVER re-generated by the model — it is
kept exactly as received from Telegram (per TZ §5, must stay unabridged).
"""
from __future__ import annotations

import re
from typing import Optional, TypedDict

import anthropic

from app.config import settings

# --- Stage 1: keyword / contact heuristics ----------------------------------

_KEYWORDS = [
    "услуг", "стоимост", "цена", "цены", "прайс", "запись", "записаться",
    "консультац", "пишите в личку", "пишите в лс", "пиши в лс", "в лс",
    "в директ", "заказ", "аренда", "сдам", "сдаю", "предлагаю", "оказываю",
    "провожу", "делаю", "изготовлю", "продам", "продаю", "доставка",
    "мастер класс", "мастер-класс", "бронирование", "бронь", "свободные слоты",
    "скидк", "акция", "рассрочка",
]

_CONTACT_RE = re.compile(
    r"(@[a-zA-Z0-9_]{4,32})"          # telegram username
    r"|(\+?\d[\d\-\s\(\)]{7,14}\d)"    # phone-like sequence
    r"|(https?://\S+)"                # any link
    r"|(t\.me/\S+)"                   # telegram link without scheme
    r"|(wa\.me/\S+)",                 # whatsapp link
    re.IGNORECASE,
)


def stage1_passes(text: str) -> bool:
    """Cheap OR-filter: keyword hit OR a contact-looking token. TZ names both
    signals but the goal here is only to drop *obvious* junk before the paid
    model call — the model in stage 2 does the precise classification, so an
    OR (not AND) keeps recall high and avoids losing real ads at this stage."""
    if not text or not text.strip():
        return False
    lowered = text.lower()
    if any(kw in lowered for kw in _KEYWORDS):
        return True
    return bool(_CONTACT_RE.search(text))


# --- Stage 2: Claude Haiku classify + extract -------------------------------

_TOOL_SCHEMA = {
    "name": "extract_service_card",
    "description": (
        "Classify whether a Telegram post is an advertisement by an expert, "
        "entrepreneur or company offering their own service, and if so "
        "extract structured fields for a CRM card."
    ),
    "input_schema": {
        "type": "object",
        "properties": {
            "is_service_ad": {
                "type": "boolean",
                "description": (
                    "true ONLY if the author is offering their own service "
                    "and inviting the reader to use it (not a question, "
                    "discussion, repost, or someone else's ad)."
                ),
            },
            "category": {
                "type": "string",
                "description": (
                    "Free-form service category in Russian, e.g. "
                    "'психология', 'аренда байков'. Empty string if "
                    "is_service_ad is false."
                ),
            },
            "first_name": {
                "type": "string",
                "description": (
                    "Author's first name — prefer an explicit name stated in "
                    "the post text, otherwise use the given profile name. "
                    "Empty string if unknown."
                ),
            },
            "last_name": {
                "type": "string",
                "description": (
                    "Author's last name — same rule as first_name. Empty "
                    "string if unknown."
                ),
            },
            "extra_contacts": {
                "type": "string",
                "description": (
                    "Phone number / link / other messenger explicitly given "
                    "in the post text, separate from the Telegram username. "
                    "Empty string if none."
                ),
            },
        },
        "required": [
            "is_service_ad", "category", "first_name", "last_name", "extra_contacts",
        ],
    },
}

_SYSTEM_PROMPT = (
    "Ты помогаешь собирать базу объявлений услуг из Telegram-каналов для "
    "будущего бота-поисковика. Тебе дают текст одного сообщения и известные "
    "данные профиля автора. Определи, является ли сообщение объявлением "
    "эксперта/предпринимателя/компании о СВОЕЙ услуге с явным предложением "
    "ей воспользоваться (а не вопросом, обсуждением, репостом чужого "
    "объявления или новостью). Если да — извлеки поля через инструмент "
    "extract_service_card. Категорию услуги определяй свободно, без "
    "фиксированного справочника."
)


class ExtractedCard(TypedDict):
    is_service_ad: bool
    category: str
    first_name: str
    last_name: str
    extra_contacts: str


_client: Optional[anthropic.Anthropic] = None


def _get_client() -> anthropic.Anthropic:
    global _client
    if _client is None:
        _client = anthropic.Anthropic(api_key=settings.anthropic_api_key)
    return _client


def classify_and_extract(
    text: str,
    profile_first_name: Optional[str],
    profile_last_name: Optional[str],
) -> Optional[ExtractedCard]:
    """Single model call: classify + extract. Returns None on an API error
    (caller should skip the message and keep going, not crash the run)."""
    client = _get_client()
    user_content = (
        f"Профиль автора: имя={profile_first_name or '-'}, "
        f"фамилия={profile_last_name or '-'}.\n\nТекст поста:\n{text}"
    )
    try:
        response = client.messages.create(
            model=settings.anthropic_model,
            max_tokens=512,
            system=_SYSTEM_PROMPT,
            tools=[_TOOL_SCHEMA],
            tool_choice={"type": "tool", "name": "extract_service_card"},
            messages=[{"role": "user", "content": user_content}],
        )
    except anthropic.APIError:
        return None

    for block in response.content:
        if block.type == "tool_use" and block.name == "extract_service_card":
            data = block.input
            return ExtractedCard(
                is_service_ad=bool(data.get("is_service_ad")),
                category=str(data.get("category") or ""),
                first_name=str(data.get("first_name") or ""),
                last_name=str(data.get("last_name") or ""),
                extra_contacts=str(data.get("extra_contacts") or ""),
            )
    return None
